### ISSUE TITLE
Research UI and Accessibility

### ISSUE THREAD

**Issue by timo1227** [timo1227/covey.town#7]

**Comment by nilmo-contreras** [comment]
# Website Accessibility Guidelines
- Provide sufficient contrast between foreground and background colors to ensure readability.
- Enable keyboard navigation for web design so that users can interact with the interface without a mouse.
- Prioritize text clarity by using simple and clear language, appropriate font size and style, and proper headings and structure.
- Don't rely on color exclusively to convey meaning or information, as some users may have color vision deficiencies or use different color settings.
- Order HTML content properly by following a logical and consistent sequence that matches the visual layout.
- Use explicit link text by avoiding vague phrases like "click here" or "read more" and instead describing the destination or purpose of the link.
- Use a minimum 40×40 pixel target area for touch controls to ensure that users can easily tap or click on them without accidentally activating other elements.
- Make media content accessible by providing captions, transcripts, and audio descriptions for audio and video content and alternative text for images (I don't know how feasible this would be for us).

https://wave.webaim.org/ - Great tool for determining how accessible a website is.
